name: ModuleRelease

on:
  workflow_dispatch:
  push:
    branches:
      - "+([0-9])?(.{+([0-9]),x}).x"
      - master
    paths:
      - '**/*.tpl'
      - '**/*.py'
      - '**/*.tf'
      - '.github/workflows/release.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    # Skip running release workflow on forks
    if: github.repository_owner == 'signorrayan'
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: cp .github/.releaserc.yml .
      - run: npm i -g semantic-release @semantic-release/changelog @semantic-release/git
      - run: semantic-release

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}